# Generated by Django 4.2.13 on 2024-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_deposit_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cus_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(default='GQ6HXW9M0VBMC60X', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(default='LIAFUMTUX65YPHQC', max_length=100, unique=True),
        ),
    ]
