# Generated by Django 4.2.13 on 2024-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_account_cus_img_alter_deposit_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(default='IBENUNLRCWOP6ECTD', max_length=100),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(default='0VH3ULIY9LE5UV9FK', max_length=100),
        ),
    ]
