# Generated by Django 5.0.6 on 2024-08-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_acc_no', models.CharField(default='3522341551', max_length=20, unique=True)),
                ('cus_img', models.ImageField(blank=True, null=True, upload_to='customer_images/')),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_mob', models.CharField(max_length=15)),
                ('cus_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cus_created_at', models.DateTimeField(auto_now_add=True)),
                ('cus_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
