# Generated by Django 4.2.13 on 2024-06-02 06:13

import bankapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='cus_acc_no',
            field=models.CharField(default=bankapp.models.Accounts.rand_ac, max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='trans_id',
            field=models.CharField(default=bankapp.models.Deposit.trans, max_length=16),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='trans_id',
            field=models.CharField(default=bankapp.models.Withdraw.trans, max_length=16),
        ),
    ]
