# Generated by Django 5.0.6 on 2024-08-27 17:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description_alter_course_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='highlights',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
